### ISSUE TITLE
args.n_feature

### ISSUE THREAD

**Issue by lindsey98** [xxgege/StableNet#9]
Hi,  
   May I ask should the args.n_feature be set equal to the batch size?

**Comment by JulieCarlon** [comment]
Hi, I also want to know this. Are you clear now?

**Comment by khawar-islam** [comment]
@lindsey98 @JulieCarlon Did you test the model? I am testing a StableNET model but getting an error, could you help me please?

```
model = resnet34_with_table()
# Load the model for evaluation
#model = torch.load(EVAL_MODEL)

optimizer = torch.optim.SGD(model.parameters(), 0.01,
                            momentum=0.9,
                            weight_decay=1e-4)

checkpoint = torch.load(EVAL_MODEL)
model.load_state_dict(checkpoint['model_state_dict'])
model.n_feature = 128
optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
epoch = checkpoint['epoch']
loss = checkpoint['loss']

model.eval()
```

```
Traceback (most recent call last):
  File "eval.py", line 13, in <module>
    model = resnet34_with_table(n_feature=128)
  File "/media/cvpr/CM_1/pytorch-image-classification/StableNet/models/resnet_with_table.py", line 274, in resnet34_with_table
    **kwargs)
  File "/media/cvpr/CM_1/pytorch-image-classification/StableNet/models/resnet_with_table.py", line 239, in _resnet
    model = ResNet_with_table(block, layers, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_feature'
```
